### ISSUE TITLE
Embed PlayStrategy TV in your site

### ISSUE THREAD

**Issue by ddugovic** [Mind-Sports-Games/lila#277]
The embed widget at https://playstrategy.org/developers is plainly broken.  I would like to use this widget in my livestream overlay.

**Comment by JamesHeppell** [comment]
Thanks for the interest, we are aware of the issue and it's in our long list of issues to fix. We will let you know when we are looking into it/its fixed.

**Comment by JamesHeppell** [comment]
The embedding widget should currently be working for chess (e.g. export a game), and we have updated the developers page to showcase that, however it is broken for our other games. We have an issue/task to look into this but it's not our top priority right now. 
Were you mainly looking at streaming chess or other games types?

**Comment by ddugovic** [comment]
I mainly was mainly looking at streaming chess, although I quite enjoy other games as well.  Thanks.

Perhaps I need to log in again or do something else cookie-related?  I've tried a few browsers including my OBS browser, however pieces are absent:
![image](https://user-images.githubusercontent.com/1834123/175320569-f0c152c2-d62d-4b93-8182-9edfc4dca1cd.png)

**Comment by JamesHeppell** [comment]
No the tv doesn't work for me either - sorry that bit is still on our list to fix.  You may have to embed a given (chess) game instead to get something like this working for now, instead of the tv. 
Will keep this issue open until we have fixed the tv embed, which should hopefully fix the other non-chess game embeds as we think the same issue is related. (theme pref is an array not a string anymore)
